microsoft/ApplicationInsights-Python

- DESCRIPTION.rst
- README.md
- applicationinsights/__init__.py
- applicationinsights/logging/ApplicationInsightsHandler.py
- applicationinsights/logging/__init__.py
- setup.py
- tests/applicationinsights_tests/__init__.py
- tests/applicationinsights_tests/logging_tests/TestApplicationInsightsHandler.py
- tests/applicationinsights_tests/logging_tests/__init__.py
- tests/tests.py
This adds a new sub-module: applicationinsights.logging for the purpose of logging integration. Usage:
```python
import logging
from applicationinsights.logging import ApplicationInsightsHandler
handler = ApplicationInsightsHandler('<YOUR INSTRUMENTATION KEY GOES HERE>')
logging.basicConfig(handlers=[ handler ], format='%(levelname)s: %(message)s', level=logging.DEBUG)
logging.debug('This is a message')
```
> Logging handler for Application Insights

- applicationinsights/TelemetryClient.py
exc_value.args may contain members that aren't strings, which will cause ''.join() to raise an error. Calling str on the exception will produce the message as intended by the exception creator, which for most standard exceptions is the same as ''.join(args).
It may be nice to submit each arg as a string too, but that probably needs changes elsewhere which I'm not prepared to make. `[str(a) for a in value.args]` is the best way to get a list of values to submit.
> Fix track_exception for non-str exception args

- applicationinsights/channel/SenderBase.py
`SenderBase.send_timeout` setter actually sets value to wrong field `self._send_buffer_size = seconds`
> Fix send_timeout setter

- applicationinsights/django/middleware.py
Check that a Django request object has the user attribute. This is necessary if a Django project does not have the auth middleware that sets request.user.
> Check that the request object has the user attribute

- CHANGELOG.md
- README.md
- applicationinsights/requests/WSGIApplication.py
Our Flask app cannot log common properties/dimensions when it uses the default WSGIApplication wrapper. I have updated the wrapper construct to take in a new common_properties object. This is similar to the code used in the NodeJS Application Insight Telemetry Logger: https://github.com/Microsoft/ApplicationInsights-node.js/blob/develop/Library/TelemetryClient.ts#L36
These common properties are then logged for every track_request made by the WSGIApplication wrapper.
> Add common properties argument to WSGIApplication wrapper

- README.rst
The SDK provides a first-class integration for Flask, so using Flask as the example for the generic WSGIApplication integration for the SDK might be confusing to some users. This change rewrites the example to use a "hello world" application example for Pyramid, one of the most popular web frameworks for Python to remove the potential confusion.
> Switch WSGIApplication example to Pyramid

- README.rst
The display of some of the code examples in the README is currently broken on GitHub: the code snippets don't render due to missing newlines after the `.. code:: python` block declaration. This pull request fixes that.
**Screenshot of README before this pull request:**
**Screenshot of README after this pull request:**
> Fix display of code in GitHub README preview

- CHANGELOG.md
- README.rst
- applicationinsights/TelemetryClient.py
- applicationinsights/channel/TelemetryChannel.py
- tests/applicationinsights_tests/TestTelemetryClient.py
- tests/applicationinsights_tests/exception_tests/TestEnable.py
- tests/applicationinsights_tests/logging_tests/TestLoggingHandler.py
If the event has no properties or `{}` then the context properties are not used either. Only when the event has some properties, e.g. `client.track_event('test', {"x": 42})` then the context properties are picked up. This PR adds a failing test that should succeed. I don't know what the solution is but this should help with fixing the bug.
> Fix support for context.properties

- CHANGELOG.md
- applicationinsights/flask/ext.py
The `__traceback__` attribute for exceptions was only introduced in
Python 3 so the current way of sending exception information to
Application Insights from Flask fails in Python 2. This change fixes
that by re-raising the exception and using `sys.exc_info` under the hood
to gather the exception information.
> Fix Flask integration AttributeError on Python 2

- .travis.yml
Python 3.4 will end of life in the coming weeks so let's start testing on a more up-to-date version.
* https://devguide.python.org/#branchstatus
> Travis CI: Python 3.4 --> 3.6

- applicationinsights/django/middleware.py
Follows Python porting best practice [___use feature detection instead of version detection___](https://docs.python.org/3/howto/pyporting.html#use-feature-detection-instead-of-version-detection).
> Use feature detection instead of version detection

- CHANGELOG.md
- applicationinsights/channel/NullSender.py
- tests/applicationinsights_tests/channel_tests/TestAsynchronousQueue.py
Currently the NullSender crashes when used in conjunction with AsynchronousQueue since the AsynchronousQueue relies on some methods that are not part of the SenderBase interface.
This limitation leads to unexpected behavior when for example using the NullSender to avoid sending telemetry in an application when the instrumentation key isn't configured in the environment.
This change makes the NullSender work with the AsynchronousQueue so that the class can be used with both queues included in the SDK.
> Fix bug when NullSender is used with Async Queue

- .travis.yml
- CHANGELOG.md
- applicationinsights/channel/AsynchronousQueue.py
- applicationinsights/channel/QueueBase.py
- applicationinsights/channel/SynchronousQueue.py
- tests/applicationinsights_tests/channel_tests/TestQueueBase.py
Currently the Application Insights client SDK already has some great resiliency built-in, e.g. retrying to send telemetry if there are intermittent connectivity issues or service interruptions. However,
there still is a risk to lose telemetry if the app crashes before sending telemetry since the telemetry queue is in-memory only.
This change adds an option to persist the queue to disk via the [persist-queue](https://pypi.org/project/persist-queue/) module which will protect customers against potential data loss, at the cost of a slight loss in performance.
> Add option to make the telemetry queue persistent

- CHANGELOG.md
- applicationinsights/logging/LoggingHandler.py
- tests/applicationinsights_tests/logging_tests/TestLoggingHandler.py
This removes an assumption that the log level should always be INFO by enabling users to call the function like so:
```py
import logging
from applicationinsights.logging import enable
enable('my-instrumentation-key', level=logging.DEBUG)
```
It could be argued the the same can be achieved via: `enable('key').setLevel(logging.DEBUG)`, but this somewhat leaks the logging handler implementation detail and leaves the current implicit `INFO` level undocumented.
> Add option to customize log level in enable

- CHANGELOG.md
- applicationinsights/flask/ext.py
The Flask 1.0 release changed the semantics of `@app.errorhandler(Exception)`.
Previously, this feature would catch application internal exceptions only. Since the Flask 1.0 release, this now catches all exceptions, including werkzeug's HTTPException which is used internally by Flask for control flow, e.g. 404 not found, 403 forbidden, etc. The side-effect of this change is that the AppInsights exception handler now translated these control flow exceptions into uncaught exceptions, i.e. HTTP 500 errors.
This change makes the AppInsights exception handler more robust to no longer swallow the control-flow exceptions.
Resolves https://github.com/Microsoft/ApplicationInsights-Python/issues/124
> Avoid swallowing flask control-flow exceptions

- CHANGELOG.md
- applicationinsights/logging/LoggingHandler.py
- tests/applicationinsights_tests/logging_tests/TestLoggingHandler.py
It's a very common use-case to set up AppInsights telemetry in a project
and customize the telemetry channel to be asynchronous; for example to
transparently integrate AppInsights into an existing daemon, worker
thread or webserver that already uses the logging module. It's currently
tedious if the user always has to write the same code over and over
again to import the AsynchronousQueue, AsynchronousSender,
TelemetryChannel, write them all up, before being able to pass them into
the enable function. As such, this change introduces a new shortcut that
lets the user specify async mode as a high-level concept on the enable
function.
This change simplifies the following code:
```py
from applicationinsights.logging import enable
from applicationinsights.channel import AsynchronousQueue
from …
```
> Add option to set async and endpoint in enable

- CHANGELOG.md
- applicationinsights/flask/ext.py
This enables use-cases to set custom properties to be sent along the telemetry such as a user id or a role name.
Resolves https://github.com/Microsoft/ApplicationInsights-Python/issues/136
Resolves https://github.com/Microsoft/ApplicationInsights-Python/issues/146
> Add accessor for the Flask telemetry context

- .travis.yml
- setup.py
The classifiers list in `setup.py` mentions support for Python 3.4 and yet the CI on Travis doesn't run the tests on that version which means that we can't be certain that the package works correctly on the declared version.
To fix this discrepancy, this change makes the Python versions used during CI match up with the Python versions declared in the classifiers list.
> Ensure CI and PyPI Python versions match

- applicationinsights/logging/LoggingHandler.py
- tests/applicationinsights_tests/logging_tests/TestLoggingHandler.py
The `logging.enable` function caches references to the `LoggingHandler` instances that it creates in a dictionary private to the module.
This means that references to the handler objects survive even if they were removed from all loggers that referenced them, causing two undesirable side-effects:
1) The `LoggingHandler` instances created by `logging.enable` can never be reclaimed by the garbage collector.
2) Removing all references to the `LoggingHandler` from the logger doesn't mark the instrumentation key as "no longer used" in the `logging.enable` module.
This change fixes these issues by replacing the cache with a `WeakValueDictionary`: as soon as the last reference to the `LoggingHandler` is removed (e.g. when `some_logger.removeHandler(...)` is called), the `WeakValueDictionary` …
> Fix memory leak in logging.enable

- CHANGELOG.md
- README.rst
- applicationinsights/TelemetryClient.py
- tests/applicationinsights_tests/TestTelemetryProcessor.py
Add Initial `TelemetryProcessor` support, patterning after nodejs.
> Initial checkin for TelemetryProcessor

- CHANGELOG.md
- setup.cfg
- setup.py
- src/azure/monitor/opentelemetry/distro/configurator.py
- src/azure/monitor/opentelemetry/distro/distro.py
- test-requirements.txt
- tox.ini
Added an OpenTelemetry Distro and an OpenTelemetry Configurator. These provide a way to customize auto-instrumentation. The distro sets the default exporters to the Azure Monitor exporters. The configurator does not currently add any additional functionality to the base OT configurator, but can be edited to do so in the future.
[This PR](https://github.com/Azure/azure-sdk-for-python/pull/25368) added the exporter entry points which enabled auto-instrumentation to access the exporters. Since this PR includes using those exporters as the default, auto-instrumentation will only work properly when your version of exporters include the addition of the entry points.
Testing by pointing to a version of the azure-monitor-opentelemetry-exporter with the entry points and triggering …
> Added OT Distro and Configurator

- .github/workflows/publish.yml
- CHANGELOG.md
- scripts/build.sh
Added a publish yaml and build script in the style of opentelemetry-python. However, these scripts need github secrets to be added for the mypi credentials.
> Added publish yml

- CHANGELOG.md
- azure-monitor-opentelemetry-distro/azure/monitor/opentelemetry/distro/_constants.py
- azure-monitor-opentelemetry-distro/azure/monitor/opentelemetry/distro/_diagnostic_logging.py
- azure-monitor-opentelemetry-distro/azure/monitor/opentelemetry/distro/configurator.py
- azure-monitor-opentelemetry-distro/azure/monitor/opentelemetry/distro/distro.py
- azure-monitor-opentelemetry-distro/tests/test_constants.py
- azure-monitor-opentelemetry-distro/tests/test_diagnostic_logging.py
- azure-monitor-opentelemetry-distro/tests/test_distro.py
- test-requirements.txt
Added diagnostic and status loggers. These loggers are only active in App Service environments. The status logger outputs during initialization and rewrites the file each time. It is used only to get the current status of the distro's initialization and check if something went wrong. The diagnostic logger handler's function is twofold.
1. It's added to the "opentelemetry" logger so as to capture all opentelemetry logs and send them to a file for App Service to pick up.
2. The `AzureDiagnosticLogger` class has methods through which distro-level logs can be created.
Node Loggers: https://dev.azure.com/msazure/One/_git/MGMT-AppInsights-NodeJS-IPA?path=/src/Loader.ts
> Added diagnostic logging

- CHANGELOG.md
- azure-monitor-opentelemetry-distro/README.md
- azure-monitor-opentelemetry-distro/azure/monitor/opentelemetry/distro/__init__.py
- azure-monitor-opentelemetry-distro/azure/monitor/opentelemetry/distro/distro.py
- azure-monitor-opentelemetry-distro/samples/logging/simple.py
- azure-monitor-opentelemetry-distro/tests/configuration/test_configure.py
- azure-monitor-opentelemetry-distro/tests/configuration/test_util.py
Added logging configuration to api. It includes the following options:
* disable_logging
* logging level - determines the level of the handler OTel adds to the root logger.
> Added Logging Configuration

- CHANGELOG.md
- azure-monitor-opentelemetry-distro/azure/monitor/opentelemetry/distro/_diagnostics/_diagnostic_logging.py
- azure-monitor-opentelemetry-distro/tests/diagnostics/test_diagnostic_logging.py
> Disabling diagnostics for diagnostic module. Added duplicate handler test

- CHANGELOG.md
- azure-monitor-opentelemetry-distro/README.md
- azure-monitor-opentelemetry-distro/azure/monitor/opentelemetry/distro/__init__.py
- azure-monitor-opentelemetry-distro/tests/configuration/test_configure.py
- azure-monitor-opentelemetry-distro/tests/configuration/test_util.py
> Root logger configuration

- CHANGELOG.md
- azure-monitor-opentelemetry-distro/README.md
- azure-monitor-opentelemetry-distro/azure/monitor/opentelemetry/distro/__init__.py
- azure-monitor-opentelemetry-distro/tests/configuration/test_configure.py
Fixes https://github.com/microsoft/ApplicationInsights-Python/issues/234
> Set export interval to 5 instead of 30 seconds

- CHANGELOG.md
- azure-monitor-opentelemetry-distro/README.md
- azure-monitor-opentelemetry-distro/azure/monitor/opentelemetry/distro/__init__.py
- azure-monitor-opentelemetry-distro/tests/configuration/test_configure.py
- azure-monitor-opentelemetry-distro/tests/configuration/test_util.py
Note we did not include configuring `LogRecordProcessor`s because logging is unstable. Asking the user to specify those classes may induce breaking changes.
Fixes https://github.com/microsoft/ApplicationInsights-Python/issues/236
> Add ability to add custom span processors and metric readers

- CHANGELOG.md
- azure-monitor-opentelemetry-distro/README.md
- azure-monitor-opentelemetry-distro/azure/monitor/opentelemetry/distro/distro.py
- azure-monitor-opentelemetry-distro/samples/logging/correlated_logs.py
- azure-monitor-opentelemetry-distro/samples/logging/custom_properties.py
- azure-monitor-opentelemetry-distro/samples/logging/exception_logs.py
- azure-monitor-opentelemetry-distro/samples/logging/logs_with_traces.py
- azure-monitor-opentelemetry-distro/samples/logging/simple.py
* Defaulting _OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED to true for auto-instrumentation.
* Added samples for correlated logs, exceptions, and custom properties
* Updated readme with logging_level defaulting behavior.
Fixes https://github.com/microsoft/ApplicationInsights-Python/issues/239
> Defaulting logging env var. Added logging samples

- CHANGELOG.md
- azure-monitor-opentelemetry-distro/azure/monitor/opentelemetry/distro/__init__.py
- azure-monitor-opentelemetry-distro/setup.py
Updating to the latest exporter and api/sdk.
This comes with the warning mentioned in this issue: https://github.com/open-telemetry/opentelemetry-python/issues/3102
> Update to exporter 1.0.0b12 and sdk/api 1.15

- CHANGELOG.md
- azure-monitor-opentelemetry/LICENSE
- azure-monitor-opentelemetry/MANIFEST.in
- azure-monitor-opentelemetry/azure/__init__.py
- azure-monitor-opentelemetry/azure/monitor/__init__.py
MANIFEST.in is responsible for specifying files in source distribution.
LICENSE file was missing.
Modify `__init__.py` to use `pkgutil` method since exclusion of packages in `setup.py` (azure-sdk does this for some reason so we have to follow suit for now until we switch to namespace packages)
> Fix source and wheel distribution

- CHANGELOG.md
- azure-monitor-opentelemetry/README.md
- azure-monitor-opentelemetry/azure/monitor/opentelemetry/_configure.py
- azure-monitor-opentelemetry/azure/monitor/opentelemetry/autoinstrumentation/_distro.py
- azure-monitor-opentelemetry/azure/monitor/opentelemetry/util/__init__.py
- azure-monitor-opentelemetry/azure/monitor/opentelemetry/util/configurations.py
- azure-monitor-opentelemetry/samples/tracing/db_psycopg2.py
- azure-monitor-opentelemetry/samples/tracing/django/sample/example/views.py
- azure-monitor-opentelemetry/samples/tracing/http_flask.py
- azure-monitor-opentelemetry/samples/tracing/http_requests.py
- azure-monitor-opentelemetry/tests/configuration/test_configure.py
- azure-monitor-opentelemetry/tests/configuration/test_util.py
Previously, default behavior was to enable instrumentations by passing in a configuration to name libraries that user wants to enable. This seems too tedious and adds extra code for the user.
Change default behavior to enable all instrumentations, and implement configuration to exclude certain libraries via `exclude_instrumentations` configuration. This matches with the behavior of `sitecustomize.py` in OT and in attach.
> Change default behavior of instrumentations and implement exclusion configuration

- CHANGELOG.md
- azure-monitor-opentelemetry/README.md
- azure-monitor-opentelemetry/azure/monitor/opentelemetry/_configure.py
- azure-monitor-opentelemetry/samples/tracing/http_fastapi.py
- azure-monitor-opentelemetry/samples/tracing/http_flask.py
- azure-monitor-opentelemetry/samples/tracing/http_requests.py
- azure-monitor-opentelemetry/tests/configuration/test_configure.py
```
configure_azure_monitor(
connection_string="<your-connection-string>",
instrumentation_config={
"flask": {
"excluded_urls": "http://localhost:8080/ignore",
}
},
)
```
> Change instrumentation config to use nested dictionary structure

- CHANGELOG.md
- azure-monitor-opentelemetry/azure/monitor/opentelemetry/util/configurations.py
- azure-monitor-opentelemetry/samples/logging/logs_with_traces.py
- azure-monitor-opentelemetry/tests/configuration/test_util.py
Setting the exporters to "None" is a way to disable a pillar. This logic is already used in [OTEL auto-instrumentation](https://github.com/open-telemetry/opentelemetry-python/blob/main/opentelemetry-sdk/src/opentelemetry/sdk/_configuration/__init__.py#L183)
> Infer pillar disablement from exporter env vars.

- CHANGELOG.md
- azure-monitor-opentelemetry/samples/logging/correlated_logs.py
- azure-monitor-opentelemetry/samples/logging/custom_properties.py
- azure-monitor-opentelemetry/samples/logging/exception_logs.py
- azure-monitor-opentelemetry/samples/logging/logs_with_traces.py
- azure-monitor-opentelemetry/samples/logging/simple.py
- azure-monitor-opentelemetry/samples/metrics/attributes.py
- azure-monitor-opentelemetry/samples/metrics/instruments.py
- azure-monitor-opentelemetry/samples/tracing/db_psycopg2.py
- azure-monitor-opentelemetry/samples/tracing/django/sample/example/views.py
- azure-monitor-opentelemetry/samples/tracing/http_fastapi.py
- azure-monitor-opentelemetry/samples/tracing/http_flask.py
- azure-monitor-opentelemetry/samples/tracing/http_requests.py
- azure-monitor-opentelemetry/samples/tracing/http_urllib.py
- azure-monitor-opentelemetry/samples/tracing/http_urllib3.py
- azure-monitor-opentelemetry/samples/tracing/manual.py
- azure-monitor-opentelemetry/samples/tracing/sampling.py
- azure-monitor-opentelemetry/samples/tracing/simple.py
Update samples to rely on conn str env var. Updated samples that used to have instrumentation configs with env var instructions.
> Removed conn str and added exclude

- CHANGELOG.md
- azure-monitor-opentelemetry/azure/monitor/opentelemetry/_configure.py
- azure-monitor-opentelemetry/azure/monitor/opentelemetry/_constants.py
- azure-monitor-opentelemetry/azure/monitor/opentelemetry/util/configurations.py
- azure-monitor-opentelemetry/tests/configuration/test_configure.py
- azure-monitor-opentelemetry/tests/configuration/test_util.py
Using OTEL_PYTHON_DISABLED_INSTRUMENTATIONS functionality from auto instrumentation flow
> Support OTEL_PYTHON_DISABLED_INSTRUMENTATIONS

- CHANGELOG.md
- azure-monitor-opentelemetry/README.md
- azure-monitor-opentelemetry/azure/monitor/opentelemetry/_configure.py
- azure-monitor-opentelemetry/azure/monitor/opentelemetry/_constants.py
- azure-monitor-opentelemetry/azure/monitor/opentelemetry/autoinstrumentation/_distro.py
- azure-monitor-opentelemetry/azure/monitor/opentelemetry/util/configurations.py
- azure-monitor-opentelemetry/samples/tracing/azure_core.py
- azure-monitor-opentelemetry/setup.py
- azure-monitor-opentelemetry/tests/autoinstrumentation/test_distro.py
- azure-monitor-opentelemetry/tests/configuration/test_configure.py
- azure-monitor-opentelemetry/tests/configuration/test_util.py
Adding Azure-Core Tracing Extension:
https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/core/azure-core-tracing-opentelemetry
> Enable azure core tracing

- CHANGELOG.md
- azure-monitor-opentelemetry/azure/monitor/opentelemetry/_constants.py
- azure-monitor-opentelemetry/azure/monitor/opentelemetry/diagnostics/_diagnostic_logging.py
- azure-monitor-opentelemetry/azure/monitor/opentelemetry/diagnostics/_status_logger.py
- azure-monitor-opentelemetry/tests/diagnostics/test_diagnostic_logging.py
- azure-monitor-opentelemetry/tests/diagnostics/test_status_logger.py
- azure-monitor-opentelemetry/tests/test_constants.py
Fixing a bug where the logic checking the conn str env var for attach diagnostic logging was running during manual instrumentaiton.
> Fix bug where env var logic for attach was being run for distro

- CHANGELOG.md
- azure-monitor-opentelemetry/setup.py
As per Wednesday's discussion, I am unpinning the OTel version.
> Unpin OTel version

- CHANGELOG.md
- azure-monitor-opentelemetry/azure/monitor/opentelemetry/_configure.py
- azure-monitor-opentelemetry/azure/monitor/opentelemetry/_constants.py
- azure-monitor-opentelemetry/azure/monitor/opentelemetry/util/configurations.py
- azure-monitor-opentelemetry/tests/configuration/test_configure.py
- azure-monitor-opentelemetry/tests/configuration/test_util.py
We are now leveraging OT env vars for our configuration instead of custom ones. Confirmed that OT sdk uses [OTEL_BLRP_SCHEDULE_DELAY](https://github.com/open-telemetry/opentelemetry-python/blob/main/opentelemetry-sdk/src/opentelemetry/sdk/_logs/_internal/export/__init__.py#L404) as specified [here](https://github.com/microsoft/ApplicationInsights-Python/tree/main/azure-monitor-opentelemetry#usage) in the usage docs.
Fixes https://github.com/microsoft/ApplicationInsights-Python/issues/265
PR that added these env vars to OT sdk: https://github.com/open-telemetry/opentelemetry-python/pull/3237
> Remove explicit log processor env var
